version: '3.8'

networks:
    milvus-cluster:
      name: milvus-cluster
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 172.25.0.0/24
          - gateway: 172.25.0.1

volumes:
    mysql_data: null
    milvus_data: null
    etcd_data: null
    minio_data: null
    pulsar_data: null
    zookeeper_data: null
    bookkeeper_data: null

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    volumes:
      - etcd_data:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2379/health"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
        - milvus-cluster

  pulsar:
    container_name: milvus-pulsar
    image: apachepulsar/pulsar:2.8.2
    volumes:
      - pulsar_data:/pulsar/data
    environment:
      # bin/apply-config-from-env.py script will modify the configuration file based on the environment variables
      # nettyMaxFrameSizeBytes must be calculated from maxMessageSize + 10240 (padding)
      - nettyMaxFrameSizeBytes=104867840 # this is 104857600 + 10240 (padding)
      - defaultRetentionTimeInMinutes=10080
      - defaultRetentionSizeInMB=8192
      # maxMessageSize is missing from standalone.conf, must use PULSAR_PREFIX_ to get it configured
      - PULSAR_PREFIX_maxMessageSize=104857600
      - PULSAR_GC=-XX:+UseG1GC
    command: |
      /bin/bash -c \
      "bin/apply-config-from-env.py conf/standalone.conf && \
      exec bin/pulsar standalone --no-functions-worker --no-stream-storage"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/admin/v2/persistent/public/default/__pulsar_internal_zookeeper/ledgers/available"]
        interval: 30s
        timeout: 20s
        retries: 3
    networks:
      - milvus-cluster

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - minio_data:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - milvus-cluster

  rootcoord:
    container_name: milvus-rootcoord
    image: milvusdb/milvus:v2.2.8
    command: ["milvus", "run", "rootcoord"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      PULSAR_ADDRESS: pulsar://pulsar:6650
      ROOT_COORD_ADDRESS: rootcoord:53100
    depends_on:
      - "etcd"
      - "pulsar"
      - "minio"
    networks:
        - milvus-cluster

  proxy:
    container_name: milvus-proxy
    image: milvusdb/milvus:v2.2.8
    command: ["milvus", "run", "proxy"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      PULSAR_ADDRESS: pulsar://pulsar:6650
    ports:
      - "19530:19530"
    depends_on:
        - "rootcoord"
        - "etcd"
        - "pulsar"
        - "minio"
    networks:
        - milvus-cluster

  querycoord:
    container_name: milvus-querycoord
    image: milvusdb/milvus:v2.2.8
    command: ["milvus", "run", "querycoord"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      PULSAR_ADDRESS: pulsar://pulsar:6650
      QUERY_COORD_ADDRESS: querycoord:19531
    depends_on:
      - "etcd"
      - "pulsar"
      - "minio"
    networks:
        - milvus-cluster

  querynode:
    container_name: milvus-querynode
    image: milvusdb/milvus:v2.2.8
    command: ["milvus", "run", "querynode"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      PULSAR_ADDRESS: pulsar://pulsar:6650
    depends_on:
      - "querycoord"
    networks:
        - milvus-cluster

  indexcoord:
    container_name: milvus-indexcoord
    image: milvusdb/milvus:v2.2.8
    command: ["milvus", "run", "indexcoord"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      PULSAR_ADDRESS: pulsar://pulsar:6650
      INDEX_COORD_ADDRESS: indexcoord:31000
    depends_on:
      - "etcd"
      - "pulsar"
      - "minio"
    networks:
        - milvus-cluster

  indexnode:
    container_name: milvus-indexnode
    image: milvusdb/milvus:v2.2.8
    command: ["milvus", "run", "indexnode"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      PULSAR_ADDRESS: pulsar://pulsar:6650
      INDEX_COORD_ADDRESS: indexcoord:31000
    depends_on:
      - "indexcoord"
    networks:
        - milvus-cluster

  datacoord:
    container_name: milvus-datacoord
    image: milvusdb/milvus:v2.2.8
    command: ["milvus", "run", "datacoord"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      PULSAR_ADDRESS: pulsar://pulsar:6650
      DATA_COORD_ADDRESS: datacoord:13333
    depends_on:
      - "etcd"
      - "pulsar"
      - "minio"
    networks:
        - milvus-cluster

  datanode:
    container_name: milvus-datanode
    image: milvusdb/milvus:v2.2.8
    command: ["milvus", "run", "datanode"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      PULSAR_ADDRESS: pulsar://pulsar:6650
    depends_on:
      - "datacoord"
    networks:
        - milvus-cluster

  mysql:
    image: mysql:8.0.28
    container_name: mysql
    shm_size: 2g
    environment:
      MYSQLD_USER: mysql
      # # Disable User Secret
      # MYSQL_ALLOW_EMPTY_PASSWORD: 0
      MYSQL_DATABASE: ${MYSQL_DATABASE:-milvus_meta}
      MYSQL_USER: ${MYSQL_USER:-alpha}
      MYSQL_PASSWORD: ${MYSQL_PASSWD:-developer}
      # Secret for root access
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWD:-developer}
    volumes:
      # # mysql data directory
      - mysql_data:/var/lib/mysql
    restart: on-failure
#     restart: unless-stopped
    expose:
      - 3306
      - 33060
      - 33061
    ports:
      - "3306:3306"
      - "33060:33060"
      - "33061:33061"
    healthcheck:
      test: "mysqladmin ping --silent"
      interval: 30s
      timeout: 20s
      retries: 5
    networks:
        - milvus-cluster
