# Path: .devcontainer/mongo.Dockerfile
# Place username and password in .env file, pass as environment variables, or password file
version: '3.8'
services:
  # MongoDB service
  mongo:
#    image: mongo:5.0.16
    build:
      context: .
      dockerfile: .devcontainer/mongo.Dockerfile
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - ./.devcontainer/config/mongo/mongod.conf:/etc/mongod.conf
      - ./.devcontainer/config/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  # Application service
  app:
    build:
      context: .
      dockerfile: .devcontainer/app.Dockerfile
      args:
        PORT: ${MONGO_EXPRESS_PORT}
    restart: always
    expose:
      - ${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      APP_USER: ${APP_USER}
      MONGODB_USERNAME: alpha
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_HOST: mongo
      MONGODB_PORT: ${MONGODB_PORT}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      PORT: ${MONGODB_PORT}
    depends_on:
      - mongo
      - mongo-express
    volumes:
      - .:/app

  # Mongo Express service
  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root #| MongoDB admin username
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD} #| MongoDB admin password
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo:${MONGODB_PORT}/
#      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'false'            #| Enable admin access to all databases. Send strings: `"true"` or `"false"`
#      ME_CONFIG_MONGODB_SERVER: Hyfi                   #| MongoDB container name. Use comma delimited list of host names for replica sets.
#      ME_CONFIG_MONGODB_AUTH_DATABASE: Hyfi            #| Database name
#      ME_CONFIG_MONGODB_AUTH_USERNAME: root            #| Database username
#      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${MONGODB_PASSWORD} #| Database password
#      ME_CONFIG_BASICAUTH_USERNAME    | ''              | mongo-express web username
#      ME_CONFIG_BASICAUTH_PASSWORD    | ''              | mongo-express web password
#      ME_CONFIG_MONGODB_PORT: 27017                     #| MongoDB port
#      ME_CONFIG_MONGODB_SERVER: mongo                   #| MongoDB container name. Use comma delimited list of host names for replica sets.
#      ME_CONFIG_OPTIONS_EDITORTHEME   | 'default'       | mongo-express editor color theme, [more here](http://codemirror.net/demo/theme.html)
#      ME_CONFIG_REQUEST_SIZE          | '100kb'         | Maximum payload size. CRUD operations above this size will fail in [body-parser](https://www.npmjs.com/package/body-parser).
#      ME_CONFIG_SITE_BASEURL: ${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo:27017/            #| Set the baseUrl to ease mounting at a subdirectory. Remember to include a leading and trailing slash.
#      ME_CONFIG_SITE_COOKIESECRET     | 'cookiesecret'  | String used by [cookie-parser middleware](https://www.npmjs.com/package/cookie-parser) to sign cookies.
#      ME_CONFIG_SITE_SESSIONSECRET    | 'sessionsecret' | String used to sign the session ID cookie by [express-session middleware](https://www.npmjs.com/package/express-session).
#      ME_CONFIG_SITE_SSL_ENABLED      | 'false'         | Enable SSL.
#      ME_CONFIG_SITE_SSL_CRT_PATH     | ''              | SSL certificate file.
#      ME_CONFIG_SITE_SSL_KEY_PATH     | ''              | SSL key file.
    depends_on:
      - mongo

