name: Testing FastAPI, GraphQL, MongoDB, using Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
    env:
      APP_PORT: ${{ github.event.inputs.APP_PORT }}
      APP_USER: ${{ github.event.inputs.APP_USER }}
      MONGODB_USERNAME: ${{ github.event.inputs.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ github.event.inputs.MONGODB_PASSWORD }}
      MONGODB_URL: mongo
      MONGODB_PORT: 27017
      MONGODB_DATABASE: ${{ github.event.inputs.MONGODB_DATABASE }}
      MONGO_EXPRESS_PORT: 8081
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup virtual environment
        run: |
          if [ -f requirements.txt ]; then python3 -m pip install --no-cache-dir --upgrade -r requirements.txt pip; fi 

      - name: Start docker compose
        run: |
          docker-compose up -d --build --remove-orphans --force-recreate
          docker ps -a 

      - name: Execute tests
        run: |
          mkdir -p logs
          docker-compose exec -it app python3 -m pytest > logs/pytest.log
          cat logs/pytest.log
          python3 -m pytest --cov=app --cov-report=xml --cov-report=html --cov-report=term-missing --cov-fail-under=100

      - name: Stop containers
        if: always()
        run: docker-compose down
