name: Testing FastAPI, GraphQL, MongoDB, using Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_PORT: 8000
      APP_USER: alpha
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: developer
      MONGODB_URL: mongo
      MONGODB_PORT: 27017
      MONGODB_DATABASE: Hyfi
      MONGO_EXPRESS_PORT: 8081
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup virtual environment
        run: |
          python3 -m venv venv
          . venv/bin/activate

      - name: Start docker compose
        run: docker-compose up -d --build --remove-orphans --force-recreate

      - name: Execute tests
        run: pytest tests

      - name: Stop containers
        if: always()
        run: docker-compose down