name: Testing FastAPI, GraphQL, MongoDB, using Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start docker compose
        run: docker-compose -f "docker-compose.yaml" up -d --build --remove-orphans --force-recreate

      - name: Execute tests
        run: docker-compose run app pytest

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down