name: Testing FastAPI, GraphQL, MongoDB, using Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
    env:
      APP_PORT: 8000
      APP_USER: alpha
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: developer
      MONGODB_URL: mongo
      MONGODB_PORT: 27017
      MONGODB_DATABASE: Hyfi
      MONGO_EXPRESS_PORT: 8081
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup virtual environment
        run: |
          python3 -m pip install pytest
          if [ -f requirements.txt ]; then python3 -m pip install -r requirements.txt --upgrade pip; fi

      - name: Start docker compose
        run: |
          docker-compose up -d --build --remove-orphans --force-recreate
          docker ps -a 

      - name: Execute tests
        run: |
          python3 -m pytest 
          

      - name: Stop containers
        if: always()
        run: docker-compose down
